### ISSUE TITLE
Hosting platform credits

### ISSUE THREAD

**Issue by Anakin100100** [po8klasie/po8klasie-rails-api#11]
During our last meeting we discussed the need to choose a hosting platform and how we are going to set up semi-permanent backend deployment to be publicly available before the end of the next week. We have to consider major cloud providers that offer free credits for open source projects. Out of the three major cloud providers GCP doesn't seem to offer any available programs while Azure and AWS have their programs that we could apply to. @micorix can you create some sort of plan what you would like to achive with this semi-permanent deployment and what is available budget?

Azure program: https://opensource.microsoft.com/azure-credits#credits-apply
AWS program: https://pages.awscloud.com/AWS-Credits-for-Open-Source-Projects

**Comment by micorix** [comment]
Sure I can check this out but what is wrong with our current GCP setup?

**Comment by Anakin100100** [comment]
size pretty much. The 0.6 gb of ram is not enough for the database, the next server and the rails server. The setup where everything is run on a single machine on docker compose does not scale at all, does not provide any tracability and is cumbersome to maintain. Does this setup enable us to utilise any cicd?

**Comment by micorix** [comment]
1. When it comes to CI, we have set it up using GitHub Actions in both po8klasie/po8klasie and po8klasie/po8klasie-api repos.

2. As I don't feel that confident talking about infra, maybe @mlazowik 's input would be useful.

3. I would prefer to stick with GCP though.

**Comment by mlazowik** [comment]
> does not scale at all

As long as the website is completely static the current setup scales to ~inf, it's pretty much a glorified lazy scraper. Every url that is ever fetched is cached forever in cloudflare, witch cache clear after each deployment. See the README at https://github.com/po8klasie/infra for more details.

Of course if we are certain enough that variable content (user accounts) is going to be added this won't cut it and we need to do proper load testing to estimate required resources (we could still route anon requests through cache tho).

> is cumbersome to maintain
Why? Everything apart from bringing up a new deployment is automated.

> The 0.6 gb of ram is not enough for the database, the next server and the rails server.
It was enough for django + postgres, I'm not sure what are the baseline numbers for next + rails + postgres.

> Does this setup enable us to utilise any cicd?
As @micorix mentioned we do both ci and cd via github actions.

**Comment by mlazowik** [comment]
> does not provide any tracability
That's (almost?) true, to see logs you have to ssh into the instance and get them via `docker-compose`. We could look how easy would it be (I bet trivial) and how much $$ would it cost (no idea) to ship them to stackdriver.

What we do have is sentry for both django backend and frontend, could be added to rails as well.

Btw. I'm not against switching clouds, I'd just prefer to avoid unnecessary work. Looking into the open source credits terms now.

**Comment by mlazowik** [comment]
In both Azure and AWS we'd have to remember to re-apply every year. To apply to AWS we need to have an account with valid payment method attached first.

**Comment by micorix** [comment]
I recently found out that New Relic offers free tier with no credit card requirement (max 100GB of ingested data per month). Maybe it's sth worth checking in terms of logs forwarding.

https://newrelic.com/pricing

**Comment by Anakin100100** [comment]
I have seen a few posts where the next server takes more than 1 gb of ram. The next thing is that rails  by itself maybe could alone run on 0.5 gb but it would be spreading it really thin. Our data strategy is based on regenerating the whole database from scratch whenever the data changes and these jobs would be certain to cause OOM error. We are going to have around 10k records to be querried so that's not too bad but the querries we are going to run are not the most trivial. The next thing is that we are going to need redis for database query caching. We would either need a much costier vm or to use some sort of managed container service like AWS Fargate, Azure Container Instances or GCP Cloud Run or use GCP App Engine. The Redis and Postgres have to be separated and AWS offers free SQL database (1gb ram 1vcpu) and redis instance (1vcpu 0.5gb ram) for 12 months. We could run the rails app on app engine because there is 28h per day of F4_1G instance which has 2gb of ram and the next server could be set up on a free aws instance (1gb ram 1vcpu).  @micorix @mlazowik What do you think about it?

**Comment by Anakin100100** [comment]
@micorix GCP offers 50gb of logs stored for free so if we take a log retention period of two weeks we would have to generate around 3gb of logs per day which is almost certainly never going to happen. GCP integration will be much more native and easier to use than having a separate one.

**Comment by Anakin100100** [comment]
@micorix what do we exactly need a next server for? Are we going to switch to some server side rendering? If we didn't need it we could run the app on vercel for example which would be much easier.

**Comment by mlazowik** [comment]
Do we definitely need a db cache, especially as there's aggressive http caching? Have you done some tests on that?

AWS has one 1vcpu 1gb ram instance included in the free tier https://aws.amazon.com/rds/free/

**Comment by Anakin100100** [comment]
We don't really if the requests for duplicated queries never hit the server. How are we going to handle the http caching?

**Comment by mlazowik** [comment]
We already do that, via cloudflare, see https://github.com/po8klasie/infra for details

**Comment by Anakin100100** [comment]
Ok then we don't need redis

**Comment by Anakin100100** [comment]
I think we got a little sidetracked on the details of the infrastructure. @micorix please create the aws account because we are going to need it regardless for the 12 months of free sql database. Can you create a google doc (not public) for us to collaborate on both application forms?

**Comment by Anakin100100** [comment]
We decided not to pursue programs from Azure and AWS because even if we got some money from them we would have reapply every 12 months during a meeting on 16.02.2022. We also decided on keeping the current infrastructure model with increased available resources.
