### ISSUE TITLE
Creating a cloudflare client for clearing the cache after database regeneration

### ISSUE THREAD

**Issue by Anakin100100** [po8klasie/po8klasie-rails-api#12]
We decided on caching the requests inside Coudflare instead of caching the database queries server side using redis. This necessitates having a client to do that. There exists a [wrapper](https://github.com/socketry/cloudflare) for cloudflare api but is not maintained for a long time and not compatible with ruby 3.x. Switching ruby versions is not an option due to massive performance difference between ruby 3.x and 2.x. Also we are going to migrate soon to ruby 3.1 which is going to bring further 20% performance increase due to implementation of a new JIT compiler. @micorix can you give me access to our Cloudflare account or create a separate user profile with access to our account for me (I'm not familiar with how Cloudflare handles access for multiple developers) ?

**Comment by mlazowik** [comment]
How/when is the regeneration going to be run? I'm assuming it'll be a script that will be called periodically?

If by GitHub actions – there's an existing action for purging cache. If cron – it does not have to be run from ruby either, can be any existing CLI client.

**Comment by Anakin100100** [comment]
It is going to be run manually as a series of jobs on the rails server. Clearing the cache via github actions would require very careful authentication between the server and workflow runner which is a potential security risk. The whole setup where the server is waiting for the webhook with the result is not very elegant. The job would have to poll the db for the result and there is a lot of hassle with that implementation. On second thought simply clearing the cache manually would be the simplest solution. @micorix do we have any strategy for managing access to our accounts at an organizational level? If not we should design one in the near future. Sharing passwords in private messages or emails won't be very secure in the long run.

**Comment by mlazowik** [comment]
How will the jobs be scheduled? Can it be via cron? If it's via cron we can make a bash script that first calls the regeneration rails script and then the cloudflare cache clear script, which can be just a call to an existing CLI binary.

**Comment by micorix** [comment]
@Anakin100100 @mlazowik maybe it will be easier to schedule a call? 🙂

**Comment by Anakin100100** [comment]
I don't think it's really necessary. We should talk about it at our weekly call on Wednesday.

**Comment by Anakin100100** [comment]
@mlazowik for now it is going to be done only manually. In the future when working with many data providers it would make sense to regenerate the database daily but it would be an overkill for now. For now our goal is to deliver a usable version of the backend before the end of next week.

**Comment by mlazowik** [comment]
Got it, in that case I'd do a manually triggered GitHub action that talks directly with cloudflare API (there is already an official one, we've been using it for some time). This way there's less people that need direct cloudflare access and less chance of mistakes.
