### ISSUE TITLE
Creating a pull request from data_filtering branch to master

### ISSUE THREAD

**Issue by Anakin100100** [po8klasie/po8klasie-rails-api#20]
When I created the data_filtering branch I started it from the gdynia_extra_data branch because it contained the needed code but now when I want to create a pull request from the data_filtering branch to the gdynia_extra_data branch git sees all the changes from gdynia_extra_data branch that are present in data_filtering branch even though they have already been merged. @wojtodzio should I rebase from master to the data_filtering branch?

**Comment by wojtodzio** [comment]
Yeah, it seems like `gdynia_extra_data` was squashed and merged (i.e., [it's visible as only one commit on master](https://github.com/po8klasie/po8klasie-rails-api/commits/master)), and so when comparing `data_filtering` to master, git sees only two commits on master (the result of the squashing) vs. 31 commits on `data_filtering`, which is the reason it can't merge it automatically.
Rebasing would be the more elegant solution, but it will likely result in many conflicts. An alternative is to first merge master to `data_filtering` - it will result in a slightly less clear history, but you can squash it later, and it will likely save you from resolving conflicts.
If you have any issues with that, let me know, and we can do a quick pairing.

**Comment by Anakin100100** [comment]
@wojtodzio after correct rebase locally I'm unable to push the updates to master.

**Comment by Anakin100100** [comment]
nevemind I succeded in creating the pr

**Comment by micorix** [comment]
Yeah, our default org policy is that master is protected and merge strategy is squash and merge.
