### ISSUE TITLE
Usage data collection

### ISSUE THREAD

**Issue by Anakin100100** [po8klasie/po8klasie-rails-api#24]
Our current caching model (agressive request caching inside cloudflare) makes us blind to how our users use our app. With server side query caching inside redis we would be able to gather impersonal data that would be invaluable when making decisions about the future development. We would be able to gather info and run analytics on:
 - where are our users coming from (just the general area)
 - what types of queries are run most often 
 - what types of schools are they looking for
 - how new features impact the user behaviour
 - how relevant are certain data types from different data providers. 
This is just some of the info we would be able to get from using server side caching. There are probably more sophisticated things that we could get insight into. We could expose that data as a public api as well. @micorix @wojtodzio what do you think about it?

**Comment by micorix** [comment]
We use Matomo on the frontend (likely to be replaced with plausible/any other more lightweight alternative soon)

Setting up Redis requires additional resources which we would be billed for.

Anyway, configuring Redis (taking into account the features you listed above) SHOULD NOT BE considered a priority IMO. Redis is not necessary for the app to run. It's better to focus on getting our app deployed so it can serve its purpose as soon as possible.

**Comment by Anakin100100** [comment]
Sure this is not a priority but a next logical step. We are wrapping up the code review for the data filtering and this would be the next thing to tackle. 

When it comes to cost it wouldn't put too much strain on the budget. Any increase in ram size that would be required if at all would only increase the cost of production env (no real workload on staging) and the resource that would need to be increased is memory. In worst case scenarion adding 2gb of ram extra for redis is only 1.34466 usd per gb with 1 year commited use discount. 

For starters we could set the memory limit for redis to 256mb and increase it only if need be. Losing writes to redis in this case wouldn't be a problem.
