### ISSUE TITLE
Prepare docs on deployment

### ISSUE THREAD

**Issue by micorix** [po8klasie/po8klasie-rails-api#33]
Prepare docs on how to prepare rails app for deployment. I don't mean infra stuff but for example which env vars are needed, any possible shortcomings etc, so I can setup the infra smoothly.

@Anakin100100 please specify ETA

**Comment by Anakin100100** [comment]
@micorix  I don't see there more issues that could arise if we already dealt with all issues with the database conncectivity and data population. If we encounter some the solutions to them should be added to the docs but beyond that I don't see much to be added to the docs as of now. I added a deployment.md that summarises the deployment process but there isn't too much new info there. If there are some areas of the deployment that you would like to receive more clarification I'm glad to help you.
