### ISSUE TITLE
Add new filtering strategies

### ISSUE THREAD

**Issue by micorix** [po8klasie/po8klasie-rails-api#41]
We need filters for:
* school name (already covered) (fuzzy search #40)
* classes - multiple choice. If school have X class OR Y class OR Z class etc.
* same for foreign_languages and sport facilitates.

Filters input should be derived from query string value separated by comma eg. classes=foo,bar,fizz.

Please keep in mind, that classes data might be divided into years and joined with extended subjects info in the near future. Unfortunately, I am not able to provide any further info rn, coz it depends on Gdynia API provider.

Please specify an ETA

**Comment by Anakin100100** [comment]
@micorix I think that we don't really need to have the extended subjects and class profiles from the past offered in the main search functionality. I don't think anybody would want to search an entire region based on what was offered some time ago. This could be lazy loaded on a page when the entire school is displayed.  Searching on the joined string field of only currently offered extended subjects and classes would be really easy and fast as well. What do you think about that?

**Comment by micorix** [comment]
Yeah. What I meant is:
1. Users should be able to filter by current classes & extended subjects data
2. During non-recruitment period (June-March) we should provide them with filters by latest classes, extended subjects we have in db (so already past, bc current ones we won't have till April)

Would that be ok?

**Comment by Anakin100100** [comment]
yes that shouldn't be a problem

**Comment by micorix** [comment]
Great

**Comment by Anakin100100** [comment]
Implemented in #42
